name: Generate Stats Images

on:
  push:
    branches:
      - master
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29
        with:
          version: 0.15.2

      - name: Clone and build github-stats
        run: |
          git clone --depth=1 --branch master https://github.com/jstrieb/github-stats.git
          cd github-stats
          zig build --release
          cp zig-out/bin/github-stats ../github-stats-bin

      - name: Checkout history branch
        run: |
          git config --global user.name "jstrieb/github-stats"
          git config --global user.email "github-stats[bot]@jstrieb.github.io"
          git fetch origin generated:generated || true
          git checkout generated || git checkout --orphan generated

      - name: Generate images
        run: |
          ./github-stats-bin
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXCLUDE_REPOS: ${{ secrets.EXCLUDE_REPOS }}
          EXCLUDE_LANGS: ${{ secrets.EXCLUDE_LANGS }}
          EXCLUDE_PRIVATE: "false"
          DEBUG: "false"
          MAX_RETRIES: "5"

      - name: Commit to the repo
        run: |
          git add .
          git commit -m 'Update generated files' || true
          git push --set-upstream origin generated
